services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "15435:5432"
    volumes:
      - exploration_final_project_postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7.2.4
    restart: always
    ports:
      - "16379:6379"

volumes:
  exploration_final_project_postgres_data:
    name: exploration_final_project_postgres_data
