packages:
  - apps/*
  - packages/*

overrides:
  "@qdrant/js-client-rest": 1.18.0

allowBuilds:
  esbuild: true
  lightningcss: true
  prisma: true
  "@prisma/engines": true
  onnxruntime-node: true
  protobufjs: true
  sharp: false
  msgpackr-extract: false

minimumReleaseAgeExclude:
  - '@anvia/core@1.2.0'
  - '@anvia/lens@1.1.3'
  - '@anvia/otel@1.1.3'
  - '@anvia/logger@1.1.3'
  - '@anvia/openai@1.1.3'
  - '@anvia/qdrant@1.1.3'
  - '@anvia/transformers@1.1.3'
  - '@anvia/client@1.1.3'
  - '@anvia/memory-prisma@1.1.3'
  - '@anvia/server@1.1.3'
  - '@anvia/react-ui@1.1.3'
  - '@anvia/react@1.1.3'
